# Generated by Django 4.1.9 on 2023-09-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_question_answer_alter_question_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
